# Generated by Django 5.2.8 on 2025-12-16 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSaber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Área do Saber',
                'verbose_name_plural': 'Áreas do Saber',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Ocupação',
                'verbose_name_plural': 'Ocupações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Avaliação')),
            ],
            options={
                'verbose_name': 'Tipo de Avaliação',
                'verbose_name_plural': 'Tipos de Avaliação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=2, unique=True, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'UF',
                'verbose_name_plural': 'UFs',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('area_saber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.areasaber', verbose_name='Área do Saber')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='InstituicaoEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Site')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Instituição de Ensino',
                'verbose_name_plural': 'Instituições de Ensino',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('carga_horaria_total', models.IntegerField(verbose_name='Carga Horária Total (horas)')),
                ('duracao_meses', models.IntegerField(verbose_name='Duração (meses)')),
                ('area_saber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.areasaber', verbose_name='Área do Saber')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.instituicaoensino', verbose_name='Instituição')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('nome_do_pai', models.CharField(max_length=255, verbose_name='Nome do Pai')),
                ('nome_da_mae', models.CharField(max_length=255, verbose_name='Nome da Mãe')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cidade', verbose_name='Cidade')),
                ('ocupacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ocupacao', verbose_name='Ocupação')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição da Ocorrência')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data do Registro')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.curso', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.disciplina', verbose_name='Disciplina')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.pessoafisica', verbose_name='Pessoa Envolvida')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Aula')),
                ('numero_faltas', models.IntegerField(verbose_name='Número de Faltas')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.curso', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.disciplina', verbose_name='Disciplina')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.pessoafisica', verbose_name='Pessoa (Aluno)')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
                'ordering': ['data', 'disciplina'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Avaliação')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Obtida')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.curso', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.disciplina', verbose_name='Disciplina')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.pessoafisica', verbose_name='Pessoa Avaliada')),
                ('tipoavaliacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tipoavaliacao', verbose_name='Tipo de Avaliação')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['disciplina', 'pessoa'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Turma')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.curso', verbose_name='Curso')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.uf', verbose_name='UF'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_previsao_termino', models.DateField(verbose_name='Previsão de Término')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.curso', verbose_name='Curso')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.instituicaoensino', verbose_name='Instituição')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.pessoafisica', verbose_name='Pessoa (Estudante)')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['pessoa'],
                'unique_together': {('pessoa', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='DisciplinaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária (h)')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.curso', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.disciplina', verbose_name='Disciplina')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Disciplina por Curso',
                'verbose_name_plural': 'Disciplinas por Curso',
                'ordering': ['curso', 'disciplina'],
                'unique_together': {('curso', 'disciplina')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('nome', 'uf')},
        ),
    ]
