# Generated by Django 5.2.8 on 2025-12-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PessoaFisica',
            new_name='Cadastro',
        ),
        migrations.AlterModelOptions(
            name='cadastro',
            options={'verbose_name': 'Cadastro', 'verbose_name_plural': 'Cadastros'},
        ),
    ]
