from django.contrib import admin
from django.urls import include, path
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('cursos/', CursosView.as_view(), name='cursos'),
    path('cursos/novo/', CursoCreate.as_view(), name='curso_novo'),
    path('cursos/editar/<int:pk>/', CursoUpdate.as_view(), name='curso_editar'),
    path('cursos/excluir/<int:pk>/', CursoDelete.as_view(), name='curso_excluir'),
    path('disciplinas/', DisciplinasView.as_view(), name='disciplinas'),
    path('turmas/', TurmasView.as_view(), name='turmas'),
    path('turmas/novo/', TurmaCreate.as_view(), name='turma_novo'),
    path('turmas/editar/<int:pk>/', TurmaUpdate.as_view(), name='turma_editar'),
    path('turmas/excluir/<int:pk>/', TurmaDelete.as_view(), name='turma_excluir'),
    path('cadastros/', CadastroView.as_view(), name='cadastros'),
    path('cadastros/novo/', CadastroCreate.as_view(), name='cadastro_novo'),
    path('cadastros/editar/<int:pk>/', CadastroUpdate.as_view(), name='cadastro_editar'),
    path('cadastros/excluir/<int:pk>/', CadastroDelete.as_view(), name='cadastro_excluir'),
    path('instituicoes/', InstituicoesView.as_view(), name='instituicoes'),
    path('areas/', AreasView.as_view(), name='areas'),
    path('cidades/', CidadesView.as_view(), name='cidades'),
    path('matriculas/', MatriculasView.as_view(), name='matriculas'),
    path('matriculas/novo/', MatriculaCreate.as_view(), name='matricula_novo'),
    path('matriculas/editar/<int:pk>/', MatriculaUpdate.as_view(), name='matricula_editar'),
    path('matriculas/excluir/<int:pk>/', MatriculaDelete.as_view(), name='matricula_excluir'),
    path('ocorrencias/', OcorrenciasView.as_view(), name='ocorrencias'),
    path('ocorrencias/novo/', OcorrenciaCreate.as_view(), name='ocorrencia_novo'),
    path('ocorrencias/editar/<int:pk>/', OcorrenciaUpdate.as_view(), name='ocorrencia_editar'),
    path('ocorrencias/excluir/<int:pk>/', OcorrenciaDelete.as_view(), name='ocorrencia_excluir'),
    path('frequencias/', FrequenciasView.as_view(), name='frequencias'),
    path('frequencias/novo/', FrequenciaCreate.as_view(), name='frequencia_novo'),
    path('frequencias/editar/<int:pk>/', FrequenciaUpdate.as_view(), name='frequencia_editar'),
    path('frequencias/excluir/<int:pk>/', FrequenciaDelete.as_view(), name='frequencia_excluir'),
    path('avaliacoes/', AvaliacoesView.as_view(), name='avaliacoes'),
    path('avaliacoes/novo/', AvaliacaoCreate.as_view(), name='avaliacao_novo'),
    path('avaliacoes/editar/<int:pk>/', AvaliacaoUpdate.as_view(), name='avaliacao_editar'),
    path('avaliacoes/excluir/<int:pk>/', AvaliacaoDelete.as_view(), name='avaliacao_excluir'),
]

